### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dot166** [h4sh5/ghidra-headless-decompile#2]
ERROR Failed to find script in any script directory: /home/dot_______166/ghidra-headless-decompile/Decompile.java (GhidraScriptUtil)                                                                                                            ERROR REPORT SCRIPT ERROR: Decompile.java : Failed to find source bundle containing script: /home/dot_______166/ghidra-headless-decompile/Decompile.java (HeadlessAnalyzer) java.lang.ClassNotFoundException: Failed to find source bundle containing script: /home/dot_______166/ghidra-headless-decompile/Decompile.java                                                      at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:122)                                          at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:85)                                   at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:895)                                  at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1057)                                 at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1550)                          at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1688)                              at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1753)                              at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:445)                                    at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:121)                                            at ghidra.GhidraLauncher.launch(GhidraLauncher.java:59)                                                                 at ghidra.Ghidra.main(Ghidra.java:47)

**Comment by dot166** [comment]
if this helps:

OS: Ubuntu 22.04.3 LTS on Windows 10 x86_64
Ghidra Version: 10.1

**Comment by dot166** [comment]
@h4sh5

**Comment by dot166** [comment]
The issue is in ghidra
